helmfiles:
- path: ../traefik-public/helmfile.yaml

environments:
  {{ .Environment.Name }}:
    values:
    - domain: {{ exec "../../scripts/get_domain.sh" (list .Environment.Name) }}
    - ../../environments/default.yaml.gotmpl

releases:
- name: {{ .Environment.Name }}-myapp
  namespace: {{ .Environment.Name }}-services
  chart: ../../charts/myapp
  version: 0.1.2
  values:
    - values.yaml.gotmpl
