helmfiles:
- path: ../namespaces/helmfile.yaml

repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com

environments:
  default:
    values:
      - ../../environments/dev.yaml.gotmpl
      - domain: {{ exec "../../scripts/get_domain.sh" (list "") }}

releases:
- name: traefik-public
  namespace: system
  chart: stable/traefik
  labels:
    name: traefik-public
  version: 1.86.2
  values:
    - values.yaml.gotmpl
  secrets:
    - secrets.yaml
