helmfiles:
- path: ../dns/helmfile.yaml

repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com

environments:
  {{ .Environment.Name }}:
    values:
    - ../../environments/default.yaml.gotmpl

releases:
- name: traefik-public
  namespace: dev-system
  chart: stable/traefik
  labels:                                  # Arbitrary key value pairs for filtering releases
    name: traefik-public
  version: 1.86.2
  values:
    - values.yaml.gotmpl
  secrets:
    - secrets.yaml
