helmfiles:
- path: ../namespaces/helmfile.yaml

repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com

environments:
  {{ .Environment.Name }}:
    missingFileHandler: Warn      # Allows missing environment yaml template
    values:
    - domain: {{ exec "../../scripts/get_domain.sh" (list .Environment.Name) }}
    - ../../environments/default.yaml.gotmpl
    - ../../environments/{{ .Environment.Name }}.yaml.gotmpl

releases:
- name: {{ .Environment.Name }}-dns
  namespace: {{ .Environment.Name }}-system
  chart: stable/external-dns
  labels: 
    name: {{ .Environment.Name }}-dns
    environment: {{ .Environment.Name }}
  version: 2.20.4
  values:
    - values.yaml.gotmpl
  secrets:
    - secrets.yaml
