helmfiles:
- path: ../traefik-public/helmfile.yaml

environments:
  default:
    values:
      - ../../environments/dev.yaml.gotmpl
      - domain: {{ exec "../../scripts/get_domain.sh" (list "") }}

releases:
- name: myapp
  namespace: services
  chart: ../../charts/myapp
  version: 0.1.2
  values:
    - values.yaml.gotmpl
