helmfiles:
- path: ../traefik-public/helmfile.yaml

environments:
  dev:
    values:
    - ../../environments/dev.yaml.gotmpl

releases:
- name: dev-myapp                            # name of this release
  namespace: dev-services             # target namespace
  chart: ../../charts/myapp     # the chart being installed to create this release, referenced by `repository/chart` syntax
  version: 0.1.2
  values:
    - values.yaml.gotmpl
