helmfiles:
- path: ../dns/helmfile.yaml

repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com

environments:
  {{ .Environment.Name }}:
    missingFileHandler: Warn      # Allows missing environment yaml template
    values:
    - domain: {{ exec "../../scripts/get_domain.sh" (list .Environment.Name) }}
    - ../../environments/default.yaml.gotmpl
    - ../../environments/{{ .Environment.Name }}.yaml.gotmpl

releases:
- name: {{ .Environment.Name }}-traefik-public
  namespace: {{ .Environment.Name }}-system
  chart: stable/traefik
  labels:
    name: traefik-public
  version: 1.86.2
  values:
    - values.yaml.gotmpl
  secrets:
    - secrets.yaml
