helmfiles:
- path: ../traefik-public/helmfile.yaml

environments:
  {{ .Environment.Name }}:
    values:
    - domain: {{ exec "../../scripts/get_domain.sh" (list "dev-system") }}

releases:
- name: myapp                            # name of this release
  namespace: dev-services             # target namespace
  chart: ../../charts/myapp     # the chart being installed to create this release, referenced by `repository/chart` syntax
  version: 0.1.2
  values:
    - values.yaml.gotmpl
