helmfiles:
- path: ../namespaces/helmfile.yaml

repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com

environments:
  {{ .Environment.Name }}:
    values:
{{- if eq .Environment.Name "dev" }}
    - ../../environments/{{ .Environment.Name }}.yaml.gotmpl
{{- else }}
    - ../../environments/default.yaml.gotmpl
{{- end }}

releases:
- name: {{ .Environment.Name }}-dns
  namespace: {{ .Environment.Name }}-system
  chart: stable/external-dns
  labels: 
    name: {{ .Environment.Name }}-dns
    environment: {{ .Environment.Name }}
  version: 2.20.4
  values:
    - values.yaml.gotmpl
  secrets:
    - secrets.yaml
