helmfiles:
- path: ../dns/helmfile.yaml

repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: incubator
  url: https://kubernetes-charts-incubator.storage.googleapis.com

environments:
  # The "default" environment is available and used when `helmfile` is run without `--environment NAME`.
  default:
    values:
    - ../../environments/default.yaml.gotmpl
  dev:
    values:
    - ../../environments/default.yaml.gotmpl

releases:
- name: {{ .Environment.Name }}-traefik-public
  namespace: {{ .Environment.Name }}-system
  chart: stable/traefik
  labels:                                  # Arbitrary key value pairs for filtering releases
    name: traefik-public
    environment: {{ .Environment.Name }}
  version: 1.86.2
  values:
    - values.yaml.gotmpl
  secrets:
    - secrets.yaml
